################################################################################
#
#  This file is part of SplashSync Project.
#
#  Copyright (C) Splash Sync <www.splashsync.com>
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
#  For the full copyright and license information, please view the LICENSE
#  file that was distributed with this source code.
#
#  @author Bernard Paquier <contact@splashsync.com>
#
################################################################################

################################################################
# Set any variables we need
variables:
  # Configure mysql environment variables (https://hub.docker.com/r/_/mysql/)
  MYSQL_DATABASE:           wordpress
  MYSQL_ROOT_PASSWORD:      admin
  DOCKER_DRIVER:            overlay2
  COMPOSER_MEMORY_LIMIT:    -1
  BUILD_DIR:                /var/www/html
  PLUGIN_DIR:               /var/www/html/wp-content/plugins/splash-connector

################################################################
# Defined Pipeline Stages
stages:
  - deploy
  - tests

################################################################
# Functional Tests
################################################################

.functionnal:   &functionnal
    stage:      tests
    tags:       ['Dedicated']
    services:
        - name: mysql:5.7
    ################################################################
    # Before Script
    before_script:
        - sh "ci/install-core.sh"
        - sh "ci/install-plugins.sh"
        - sh "$PLUGIN_DIR/ci/configure.sh"
    ################################################################
    # Test Script
    script:
        - cd "$PLUGIN_DIR"
        ################################################################
        # Run Grumphp Main Test Sequence
        - php vendor/bin/grumphp run --testsuite=travis
        - php vendor/bin/grumphp run --testsuite=csfixer
        - php vendor/bin/grumphp run --testsuite=phpstan
        ################################################################
        # Execute Phpunit Local test Sequence
        - wp plugin delete wp-multilang --allow-root
        - php vendor/bin/phpunit -c grumphp/phpunit.xml.dist --testsuite=Local
        # Execute Complete PhpUnit Tests
        - php vendor/bin/phpunit -c grumphp/phpunit.xml.dist

Wp-5.6-Php-7.4:
  image:      wordpress:5.6-php7.4
  variables:
      WORDPRESS_VERSION:     "5.6"
  <<: *functionnal

Wp-5.5-Php-7.3:
    image:      wordpress:5.5-php7.3
    variables:
      WORDPRESS_VERSION:     "5.5"
    <<: *functionnal

Wp-5.4-Php-7.2:
    image:      wordpress:5.4-php7.2
    <<: *functionnal

#################################################################
## Build Documentation
#################################################################
#pages:
#    image:      registry.gitlab.com/badpixxel-projects/php-sdk:jekyll
#    stage:      deploy
#    tags:       ['Dedicated']
#    retry:      2
#    ################################################################################
#    # Run Test Script
#    script:
#        # Run Composer to Build deps
#        - curl -s https://raw.githubusercontent.com/BadPixxel/Php-Sdk/main/ci/composer.sh  | bash
#        # Build Documentation
#        - php vendor/bin/grumphp run --tasks=build-docs
#    artifacts:
#        paths:
#            - public

#################################################################
## Build Module
#################################################################
module:
    image:      registry.gitlab.com/badpixxel-projects/php-sdk:jekyll
    stage:      deploy
    tags:       ['Dedicated']
    retry:      2
    variables:
        PLUGIN_VERSION:         "1.6.3"
        WP_ORG_RELEASE_REF:     "1.6.3"
    ################################################################################
    # Run Test Script
    script:
        # Run Composer to Build deps
        - curl -s https://raw.githubusercontent.com/BadPixxel/Php-Sdk/main/ci/composer.sh  | bash
        # Build Documentation
        - php vendor/bin/grumphp run --tasks=build-module
        # Deploy Module on Wp Plugin Repository
        - curl -s https://git-cdn.e15r.co/open-source/wp-org-plugin-deploy/raw/master/scripts/deploy.sh | bash
    artifacts:
        paths:
            - build
