################################################################################
#
#  This file is part of SplashSync Project.
#
#  Copyright (C) Splash Sync <www.splashsync.com>
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
#  For the full copyright and license information, please view the LICENSE
#  file that was distributed with this source code.
#
#  @author Bernard Paquier <contact@splashsync.com>
#
################################################################################

################################################################
# Include Pipeline Templates
include:
  - remote: 'https://raw.githubusercontent.com/BadPixxel/Php-Sdk/main/gitlab/pages.yaml'

################################################################
# Set any variables we need
variables:
  # Configure mysql environment variables (https://hub.docker.com/r/_/mysql/)
  MYSQL_DATABASE:           wordpress
  MYSQL_ROOT_PASSWORD:      admin
  DOCKER_DRIVER:            overlay2
  COMPOSER_MEMORY_LIMIT:    -1
  BUILD_DIR:                /var/www/html
  PLUGIN_DIR:               /var/www/html/wp-content/plugins/splash-connector

################################################################
# Defined Pipeline Stages
stages:
  - Tests
  - Builds

################################################################
# Functional Tests
################################################################

.functionnal:   &functionnal
    stage:      Tests
    tags:       ['Dedicated']
    retry:      2
    services:
        - name: mysql:5.7
    ################################################################
    # Before Script
    before_script:
        - sh "ci/install-core.sh"
        - sh "ci/install-plugins.sh"
        - sh "$PLUGIN_DIR/ci/configure.sh"
    ################################################################
    # Test Script
    script:
        - cd "$PLUGIN_DIR"
        ################################################################
        # Run GrumPhp Main Test Sequence
        - php vendor/bin/grumphp run --testsuite=travis
        - php vendor/bin/grumphp run --testsuite=csfixer
        - php vendor/bin/grumphp run --testsuite=phpstan
        ################################################################
        # Execute Phpunit Local test Sequence
        - wp plugin delete wp-multilang --allow-root
        - php vendor/bin/phpunit -c grumphp/phpunit.xml.dist --testsuite=Local
        # Execute Complete PhpUnit Tests
        - php vendor/bin/phpunit -c grumphp/phpunit.xml.dist

Wp-6.7-Php-8.3:
    image:                      wordpress:6.7-php8.3
    variables:
        WORDPRESS_VERSION:      "6.7"
    <<: *functionnal
    allow_failure:              true

Wp-6.6-Php-8.2:
    image:                      wordpress:6.6-php8.2
    variables:
        WORDPRESS_VERSION:      "6.6"
    <<: *functionnal
    allow_failure:              true

Wp-6.4-Php-8.2:
    image:                      wordpress:6.4-php8.2
    variables:
        WORDPRESS_VERSION:      "6.4"
        WOOCOMMERCE_VERSION:    "8.0.4"
    <<: *functionnal

Wp-6.3-Php-8.1:
    image:                      wordpress:6.3-php8.1
    variables:
        WORDPRESS_VERSION:      "6.3"
        WOOCOMMERCE_VERSION:    "8.0.4"
    <<: *functionnal

Wp-6.2-Php-8.0:
    image:                      wordpress:6.2-php8.0
    variables:
        WORDPRESS_VERSION:      "6.2"
        WOOCOMMERCE_VERSION:    "8.0.4"
    <<: *functionnal

Wp-6.1-Php-7.4:
    image:                      wordpress:6.1-php7.4
    variables:
        WORDPRESS_VERSION:      "6.1"
        WOOCOMMERCE_VERSION:    "7.9.0"
    <<: *functionnal

#################################################################
## Build Module
#################################################################
module:
    image:      registry.gitlab.com/badpixxel-projects/php-sdk:jekyll
    stage:      Builds
    tags:       ['Dedicated']
    retry:      2
    variables:
        PLUGIN_VERSION:         "2.0.7"
        WP_ORG_RELEASE_REF:     "2.0.7"
    ################################################################################
    # Run Test Script
    script:
        # Run Composer to Build deps
        - curl -s https://raw.githubusercontent.com/BadPixxel/Php-Sdk/main/ci/composer.sh  | bash
        # Build Module Zip
        - php vendor/bin/grumphp run --tasks=build-module
        # Install No Dev Libs
        - composer install --no-dev
        # Vendors files has to be committed to be used
        - git config --global user.email "git-contrib+ci@splashsync.com"
        - git config --global user.name "Splash Sync (GitLab CI)"
        - git add -f vendor && git commit -m "Add vendor files"
        # Deploy Module on Wp Plugin Repository
        - curl -s https://git-cdn.e15r.co/open-source/wp-org-plugin-deploy/raw/master/scripts/deploy.sh | bash
    artifacts:
        paths:
            - build
