################################################################################
#
#  This file is part of SplashSync Project.
#
#  Copyright (C) Splash Sync <www.splashsync.com>
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
#  For the full copyright and license information, please view the LICENSE
#  file that was distributed with this source code.
#
#  @author Bernard Paquier <contact@splashsync.com>
#
################################################################################

################################################################
# Set any variables we need
variables:
  # Configure mysql environment variables (https://hub.docker.com/r/_/mysql/)
  MYSQL_DATABASE:           wordpress
  MYSQL_ROOT_PASSWORD:      admin
  DOCKER_DRIVER:            overlay2
  COMPOSER_MEMORY_LIMIT:    -1
  BUILD_DIR:                /var/www/html
  PLUGIN_DIR:               /var/www/html/wp-content/plugins/splash-connector

################################################################
# Defined Pipeline Stages
stages:
  - tests

################################################################
# Functional Tests
################################################################

.functionnal:   &functionnal
    stage:      tests
    tags:       ['Dedicated']
    retry:      2
    services:
        - name: mysql:5.7
    ################################################################
    # Before Script
    before_script:
        - sh "ci/install-core.sh"
        - sh "ci/install-plugins.sh"
        - sh "$PLUGIN_DIR/ci/configure.sh"
    ################################################################
    # Test Script
    script:
        - cd "$PLUGIN_DIR"
        ################################################################
        # Run Grumphp Main Test Sequence
        - php vendor/bin/grumphp run --testsuite=travis
        - php vendor/bin/grumphp run --testsuite=csfixer
        - php vendor/bin/grumphp run --testsuite=phpstan
        ################################################################
        # Execute Phpunit Local test Sequence
        - wp plugin delete wp-multilang --allow-root
        - php vendor/bin/phpunit -c grumphp/phpunit.xml.dist --testsuite=Local
        # Execute Complete PhpUnit Tests
        - php vendor/bin/phpunit -c grumphp/phpunit.xml.dist

Wp-6.0-Php-7.4:
  image:      wordpress:beta-6.0-php7.4
  variables:
    WORDPRESS_VERSION:     "6.0-RC1"
  <<: *functionnal

Wp-5.9-Php-7.4:
  image:      wordpress:5.9-php7.4
  variables:
      WORDPRESS_VERSION:     "5.9"
  <<: *functionnal

Wp-5.8-Php-7.4:
  image:      wordpress:5.8-php7.4
  variables:
      WORDPRESS_VERSION:     "5.8"
  <<: *functionnal

Wp-5.7-Php-7.4:
  image:      wordpress:5.7-php7.4
  variables:
      WORDPRESS_VERSION:     "5.7"
  <<: *functionnal
