################################################################################
#
#  This file is part of SplashSync Project.
#
#  Copyright (C) Splash Sync <www.splashsync.com>
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
#  For the full copyright and license information, please view the LICENSE
#  file that was distributed with this source code.
#
#  @author Bernard Paquier <contact@splashsync.com>
#
################################################################################

################################################################
# Set any variables we need
variables:
  # Configure mysql environment variables (https://hub.docker.com/r/_/mysql/)
  MYSQL_DATABASE:           wordpress
  MYSQL_ROOT_PASSWORD:      admin
  DOCKER_DRIVER:            overlay2
  COMPOSER_MEMORY_LIMIT:    -1
  BUILD_DIR:                /var/www/html
  PLUGIN_DIR:               /var/www/html/wp-content/plugins/splash-connector

################################################################
# Defined Pipeline Stages
stages:
  - tests
  - deploy

################################################################
# Functional Tests
################################################################

.functionnal:   &functionnal
#    when:       manual
    stage:      tests
    tags:       ['Dedicated']
    services:
      - name: mysql:5.7
    ################################################################
    # Before Script
    before_script:
      - sh "ci/install-core.sh"
      - sh "ci/install-plugins.sh"
      - sh "$PLUGIN_DIR/ci/configure.sh"
    ################################################################
    # Test Script
    script:
      - cd "$PLUGIN_DIR"
      ################################################################
      # Run Grumphp Main Test Sequence
      - php vendor/bin/grumphp run --testsuite=travis
#      - php vendor/bin/grumphp run --testsuite=csfixer
#      - php vendor/bin/grumphp run --testsuite=phpstan
      ################################################################
      # Execute Phpunit Local test Sequence
#      - php vendor/bin/phpunit -c grumphp/phpunit.xml.dist --testsuite=Local
      # Execute Complete PhpUnit Tests
      - php vendor/bin/phpunit -c grumphp/phpunit.xml.dist


#Wp-1.7-Php-7.4:
#  image: registry.gitlab.com/badpixxel-projects/php-sdk:php-7.4
#  <<: *functionnal

#Ps-1.7-Php-7.2:
#  image:      prestashop/prestashop:1.7-7.2-apache
#  <<: *functionnal
#
#Wp-5.4-Php-7.2:
#    image:      registry.gitlab.com/badpixxel-projects/php-sdk:php-7.2
#    variables:
#        WP_VERSION:     "5.4"
#        WC_VERSION:     "3.9.2"
#        WP_MULTISITE:   "0"
#    <<: *functionnal
Wp-5.6-Php-7.4:
  image:      wordpress:5.6.0-php7.4
  #    variables:
  #        WP_VERSION:     "5.4"
  #        WC_VERSION:     "3.9.2"
  #        WP_MULTISITE:   "0"
  <<: *functionnal

#Wp-5.4-Php-7.2:
#    image:      wordpress:5.4-php7.2
##    variables:
##        WP_VERSION:     "5.4"
##        WC_VERSION:     "3.9.2"
##        WP_MULTISITE:   "0"
#    <<: *functionnal


#################################################################
## Build Documentation
#################################################################
pages:
  image:      registry.gitlab.com/badpixxel-projects/php-sdk:jekyll
  stage:      deploy
  tags:       ['Dedicated']
  retry:      2
  services:
    - docker:dind
  ################################################################################
  # Run Test Script
  script:
    # Run Composer to Build deps
    - curl -s https://raw.githubusercontent.com/BadPixxel/Php-Sdk/main/ci/composer.sh  | bash
    # Build Documentation
    - php vendor/bin/grumphp run --tasks=build-docs
  artifacts:
    paths:
      - public

#################################################################
## Build Module
#################################################################
module:
  image:      registry.gitlab.com/badpixxel-projects/php-sdk:php-7.2
  stage:      deploy
  tags:       ['Dedicated']
  retry:      2
  services:
    - docker:dind
  ################################################################################
  # Run Test Script
  script:
    # Run Composer to Build deps
    - curl -s https://raw.githubusercontent.com/BadPixxel/Php-Sdk/main/ci/composer.sh  | bash
    # Build Documentation
    - php vendor/bin/grumphp run --tasks=build-module
  artifacts:
    paths:
      - build
