
splash:

################################################################################    
# Configure Splash Bundle Parameters Cache    
# Cache is Enabled by Default to Store Custom Connectors Configuration
# If disabled, configuration must be store in Static, on connections section
################################################################################    
#    cache: 
#        enabled: false    
#        lifetime: 10

    # Allow Notifications for Generic Users   
    notify: ["ROLE_USER"]
    
################################################################################    
# List of Availables Connector Connections
################################################################################    

    connections:
        
        ########################################################################
        # WordPress Latest
        latest:
            id:                 ThisIsWpLatestKey
            key:                ThisTokenIsNotSoSecretChangeIt
            name:               WordPress Latest
            host:               false
            connector:          soap
            config:
                Extended:           true
                WsIdentifier:       ThisIsWpLatestKey
                WsEncryptionKey:    ThisTokenIsNotSoSecretChangeIt                
                WsHost:             http://latest.wordpress.local
                WsPath:             /wp-content/plugins/splash-connector/vendor/splash/phpcore/soap.php

        ########################################################################
        # WordPress 6.7
        wp-6-7:
            id:                 ThisIsWp67Key
            key:                ThisTokenIsNotSoSecretChangeIt
            name:               WordPress 6.7
            host:               false
            connector:          soap
            config:
                Extended:           true
                WsIdentifier:       ThisIsWp67Key
                WsEncryptionKey:    ThisTokenIsNotSoSecretChangeIt
                WsHost:             http://wp6-7.wordpress.local
                WsPath:             /wp-content/plugins/splash-connector/vendor/splash/phpcore/soap.php

        ########################################################################
        # WordPress 6.6
        wp-6-6:
            id:                 ThisIsWp66Key
            key:                ThisTokenIsNotSoSecretChangeIt
            name:               WordPress 6.6
            host:               false
            connector:          soap
            config:
                Extended:           true
                WsIdentifier:       ThisIsWp66Key
                WsEncryptionKey:    ThisTokenIsNotSoSecretChangeIt
                WsHost:             http://wp6-6.wordpress.local
                WsPath:             /wp-content/plugins/splash-connector/vendor/splash/phpcore/soap.php
